// data.js - Capacitance Hints Data

const exercisesData = {
  "Exercise O-I": {
    totalQuestions: 30,
    hints: {
      1: { text: "Hint not uploaded", image: "", audio: "" },
      2: { text: "Hint not uploaded", image: "", audio: "" },
      3: { text: "Hint not uploaded", image: "", audio: "" },
      4: { text: "Hint not uploaded", image: "", audio: "" },
      5: { text: "Hint not uploaded", image: "", audio: "" },
      6: { text: "Hint not uploaded", image: "", audio: "" },
      7: { text: "Hint not uploaded", image: "", audio: "" },
      8: { text: "Hint not uploaded", image: "", audio: "" },
      9: { text: "Hint not uploaded", image: "", audio: "" },
      10: { text: "Hint not uploaded", image: "", audio: "" },
      11: { text: "Hint not uploaded", image: "", audio: "" },
      12: { text: "Hint not uploaded", image: "", audio: "" },
      13: { text: "Hint not uploaded", image: "", audio: "" },
      14: { text: "Hint not uploaded", image: "", audio: "" },
      15: { text: "Hint not uploaded", image: "", audio: "" },
      16: { text: "Hint not uploaded", image: "", audio: "" },
      17: { text: "Hint not uploaded", image: "", audio: "" },
      18: { text: "Hint not uploaded", image: "", audio: "" },
      19: { text: "Hint not uploaded", image: "", audio: "" },
      20: { text: "Hint not uploaded", image: "", audio: "" },
      21: { text: "Hint not uploaded", image: "", audio: "" },
      22: { text: "Hint not uploaded", image: "", audio: "" },
      23: { text: "Hint not uploaded", image: "", audio: "" },
      24: { text: "Hint not uploaded", image: "", audio: "" },
      25: { text: "Hint not uploaded", image: "", audio: "" },
      26: { text: "Hint not uploaded", image: "", audio: "" },
      27: { text: "Hint not uploaded", image: "", audio: "" },
      28: { text: "Hint not uploaded", image: "", audio: "" },
      29: { text: "Hint not uploaded", image: "", audio: "" },
      30: { text: "Hint not uploaded", image: "", audio: "" }
    }
  },
  "Exercise O-II": {
    totalQuestions: 15,
    hints: {
      1: { text: "Hint not uploaded", image: "", audio: "" },
      2: { text: "Hint not uploaded", image: "", audio: "" },
      3: { text: "Hint not uploaded", image: "", audio: "" },
      4: { text: "Hint not uploaded", image: "", audio: "" },
      5: { text: "Hint not uploaded", image: "", audio: "" },
      6: { text: "Hint not uploaded", image: "", audio: "" },
      7: { text: "Hint not uploaded", image: "", audio: "" },
      8: { text: "Hint not uploaded", image: "", audio: "" },
      9: { text: "Hint not uploaded", image: "", audio: "" },
      10: { text: "Hint not uploaded", image: "", audio: "" },
      11: { text: "Hint not uploaded", image: "", audio: "" },
      12: { text: "Hint not uploaded", image: "", audio: "" },
      13: { text: "Hint not uploaded", image: "", audio: "" },
      14: { text: "Hint not uploaded", image: "", audio: "" },
      15: { text: "Hint not uploaded", image: "", audio: "" }
    }
  },
  "Exercise S": {
    totalQuestions: 20,
    hints: {
      1: { text: "Hint not uploaded", image: "", audio: "" },
      2: { text: "Hint not uploaded", image: "", audio: "" },
      3: { text: "Hint not uploaded", image: "", audio: "" },
      4: { text: "Hint not uploaded", image: "", audio: "" },
      5: { text: "Hint not uploaded", image: "", audio: "" },
      6: { text: "Hint not uploaded", image: "", audio: "" },
      7: { text: "Hint not uploaded", image: "", audio: "" },
      8: { text: "Hint not uploaded", image: "", audio: "" },
      9: { text: "Hint not uploaded", image: "", audio: "" },
      10: { text: "Hint not uploaded", image: "", audio: "" },
      11: { text: "Hint not uploaded", image: "", audio: "" },
      12: { text: "Hint not uploaded", image: "", audio: "" },
      13: { text: "Hint not uploaded", image: "", audio: "" },
      14: { text: "Hint not uploaded", image: "", audio: "" },
      15: { text: "Hint not uploaded", image: "", audio: "" },
      16: { text: "Hint not uploaded", image: "", audio: "" },
      17: { text: "Hint not uploaded", image: "", audio: "" },
      18: { text: "Hint not uploaded", image: "", audio: "" },
      19: { text: "Hint not uploaded", image: "", audio: "" },
      20: { text: "Hint not uploaded", image: "", audio: "" }
    }
  },
  "JEE Main": {
    totalQuestions: 25,
    hints: {
      1: { text: "Hint not uploaded", image: "", audio: "" },
      2: { text: "Hint not uploaded", image: "", audio: "" },
      3: { text: "Hint not uploaded", image: "", audio: "" },
      4: { text: "Hint not uploaded", image: "", audio: "" },
      5: { text: "Hint not uploaded", image: "", audio: "" },
      6: { text: "Hint not uploaded", image: "", audio: "" },
      7: { text: "Hint not uploaded", image: "", audio: "" },
      8: { text: "Hint not uploaded", image: "", audio: "" },
      9: { text: "Hint not uploaded", image: "", audio: "" },
      10: { text: "Hint not uploaded", image: "", audio: "" },
      11: { text: "Hint not uploaded", image: "", audio: "" },
      12: { text: "Hint not uploaded", image: "", audio: "" },
      13: { text: "Hint not uploaded", image: "", audio: "" },
      14: { text: "Hint not uploaded", image: "", audio: "" },
      15: { text: "Hint not uploaded", image: "", audio: "" },
      16: { text: "Hint not uploaded", image: "", audio: "" },
      17: { text: "Hint not uploaded", image: "", audio: "" },
      18: { text: "Hint not uploaded", image: "", audio: "" },
      19: { text: "Hint not uploaded", image: "", audio: "" },
      20: { text: "Hint not uploaded", image: "", audio: "" },
      21: { text: "Hint not uploaded", image: "", audio: "" },
      22: { text: "Hint not uploaded", image: "", audio: "" },
      23: { text: "Hint not uploaded", image: "", audio: "" },
      24: { text: "Hint not uploaded", image: "", audio: "" },
      25: { text: "Hint not uploaded", image: "", audio: "" }
    }
  },
  "JEE-Advanced": {
    totalQuestions: 20,
    hints: {
      1: { text: "Hint not uploaded", image: "", audio: "" },
      2: { text: "Hint not uploaded", image: "", audio: "" },
      3: { text: "Hint not uploaded", image: "", audio: "" },
      4: { text: "Hint not uploaded", image: "", audio: "" },
      5: { text: "Hint not uploaded", image: "", audio: "" },
      6: { text: "Hint not uploaded", image: "", audio: "" },
      7: { text: "Hint not uploaded", image: "", audio: "" },
      8: { text: "Hint not uploaded", image: "", audio: "" },
      9: { text: "Hint not uploaded", image: "", audio: "" },
      10: { text: "Hint not uploaded", image: "", audio: "" },
      11: { text: "Hint not uploaded", image: "", audio: "" },
      12: { text: "Hint not uploaded", image: "", audio: "" },
      13: { text: "Hint not uploaded", image: "", audio: "" },
      14: { text: "Hint not uploaded", image: "", audio: "" },
      15: { text: "Hint not uploaded", image: "", audio: "" },
      16: { text: "Hint not uploaded", image: "", audio: "" },
      17: { text: "Hint not uploaded", image: "", audio: "" },
      18: { text: "Hint not uploaded", image: "", audio: "" },
      19: { text: "Hint not uploaded", image: "", audio: "" },
      20: { text: "Hint not uploaded", image: "", audio: "" }
    }
  }
};
