// data.js - WEP Hints Data

const exercisesData = {
  "Exercise O-I": {
    totalQuestions: 70,
    hints: {
      1: { image: "", audio: "", text: "Vector concept. First find displacement vector then calculate DOT Product to get work." },
      2: { image: "", audio: "", text: "Hint not uploaded" },
      3: { image: "", audio: "", text: "Hint not uploaded" },
      4: { image: "", audio: "", text: "First calculate tension using NLM concepts. Work done by rope implies work done by tension." },
      5: { image: "", audio: "", text: "Angle between force and displacement is $60^\\circ$" },
      6: { image: "", audio: "", text: "Hint not uploaded" },
      7: { image: "", audio: "", text: "Hint not uploaded" },
      8: { image: "", audio: "", text: "Hint not uploaded" },
      9: { image: "", audio: "", text: "Hint not uploaded" },
      10: { image: "", audio: "", text: "Hint not uploaded" },
      11: { image: "", audio: "", text: "Hint not uploaded" },
      12: { image: "", audio: "", text: "Area under F-x graph is Work done." },
      13: { image: "", audio: "", text: "Hint not uploaded" },
      14: { image: "", audio: "", text: "Hint not uploaded" },
      15: { image: "", audio: "", text: "Hint not uploaded" },
      16: { image: "", audio: "", text: "Hint not uploaded" },
      17: { image: "", audio: "", text: "Hint not uploaded" },
      18: { image: "", audio: "", text: "This is similar to free fall under gravity. Find displacements using Kinematics in the given intervals. Then find work in each interval." },
      19: { image: "", audio: "", text: "Use work-energy theorem. Find kinetic energy at $x=2$m. The given $a$ is just some constant and its units have been adjusted to match the dimensions on both sides. Don't worry about that." },
      20: { image: "", audio: "", text: "Hint not uploaded" },
      21: { image: "", audio: "", text: "Hint not uploaded" },
      22: { image: "", audio: "", text: "Hint not uploaded" },
      23: { image: "", audio: "", text: "Hint not uploaded" },
      24: { image: "", audio: "", text: "Hint not uploaded" },
      25: { image: "", audio: "", text: "Hint not uploaded" },
      26: { image: "", audio: "", text: "Hint not uploaded" },
      27: { image: "", audio: "", text: "Hint not uploaded" },
      28: { image: "", audio: "", text: "Hint not uploaded" },
      29: { image: "", audio: "", text: "Hint not uploaded" },
      30: { image: "", audio: "", text: "Hint not uploaded" },
      31: { image: "", audio: "", text: "Hint not uploaded" },
      32: { image: "", audio: "", text: "Hint not uploaded" },
      33: { image: "", audio: "", text: "Hint not uploaded" },
      34: { image: "", audio: "", text: "Hint not uploaded" },
      35: { image: "", audio: "", text: "Hint not uploaded" },
      36: { image: "", audio: "", text: "Hint not uploaded" },
      37: { image: "", audio: "", text: "Hint not uploaded" },
      38: { image: "", audio: "", text: "Hint not uploaded" },
      39: { image: "", audio: "", text: "Hint not uploaded" },
      40: { image: "", audio: "", text: "Hint not uploaded" },
      41: { image: "", audio: "", text: "Hint not uploaded" },
      42: { image: "", audio: "", text: "Hint not uploaded" },
      43: { image: "", audio: "", text: "Hint not uploaded" },
      44: { image: "", audio: "", text: "Hint not uploaded" },
      45: { image: "", audio: "", text: "Hint not uploaded" },
      46: { image: "", audio: "", text: "Hint not uploaded" },
      47: { image: "", audio: "", text: "Hint not uploaded" },
      48: { image: "", audio: "", text: "Hint not uploaded" },
      49: { image: "", audio: "", text: "Hint not uploaded" },
      50: { image: "", audio: "", text: "Hint not uploaded" },
      51: { image: "", audio: "", text: "Hint not uploaded" },
      52: { image: "", audio: "", text: "Hint not uploaded" },
      53: { image: "", audio: "", text: "Hint not uploaded" },
      54: { image: "", audio: "", text: "Hint not uploaded" },
      55: { image: "", audio: "", text: "Hint not uploaded" },
      56: { image: "", audio: "", text: "Hint not uploaded" },
      57: { image: "", audio: "", text: "Hint not uploaded" },
      58: { image: "", audio: "", text: "Hint not uploaded" },
      59: { image: "", audio: "", text: "Hint not uploaded" },
      60: { image: "", audio: "", text: "Hint not uploaded" },
      61: { image: "", audio: "", text: "Hint not uploaded" },
      62: { image: "", audio: "", text: "Hint not uploaded" },
      63: { image: "", audio: "", text: "Hint not uploaded" },
      64: { image: "", audio: "", text: "Hint not uploaded" },
      65: {
        image: "",
        audio: "",
        text: `In Indian physics problems (especially Mechanics/Inclined planes) and railway gradient problems, "1 in $n$" or "$m$ in $n$" is often defined as the rise per unit distance measured <strong>along the incline</strong> itself:
$$\\sin \\theta = \\frac{\\text{Vertical Rise}}{\\text{Distance along the Incline}} = \\frac{2}{25} = 0.08$$`
      },
      66: { image: "", audio: "", text: "Calculate DOT product- algebriac method" },
      67: { image: "", audio: "", text: "Hint not uploaded" },
      68: { image: "", audio: "", text: "Hint not uploaded" },
      69: { image: "", audio: "", text: "Hint not uploaded" },
      70: { image: "", audio: "", text: "Hint not uploaded" }
    }
  },
  "Exercise O-II": {
    totalQuestions: 42,
    hints: {
      1: { image: "", audio: "", text: "Hint not uploaded" },
      2: { image: "", audio: "", text: "Hint not uploaded" },
      3: { image: "", audio: "", text: "Hint not uploaded" },
      4: { image: "", audio: "", text: "Hint not uploaded" },
      5: { image: "", audio: "", text: "Hint not uploaded" },
      6: { image: "", audio: "", text: "Hint not uploaded" },
      7: { image: "", audio: "", text: "Hint not uploaded" },
      8: { image: "", audio: "", text: "Hint not uploaded" },
      9: { image: "", audio: "", text: "Hint not uploaded" },
      10: { image: "", audio: "", text: "Hint not uploaded" },
      11: { image: "", audio: "", text: "This is a central force and hence conservative. Path independent work. $(x^2 + y^2)^{3/2} = r$ and $text: `$x\\hat{i} + y\\hat{j} = \\vec{r}$`$ " },
      12: { image: "", audio: "", text: "Hint not uploaded" },
      13: { image: "", audio: "", text: "Hint not uploaded" },
      14: { image: "", audio: "", text: "Hint not uploaded" },
      15: { image: "", audio: "", text: "Hint not uploaded" },
      16: { image: "", audio: "", text: "Hint not uploaded" },
      17: { image: "", audio: "", text: "Hint not uploaded" },
      18: { image: "", audio: "", text: "Hint not uploaded" },
      19: { image: "", audio: "", text: "Hint not uploaded" },
      20: { image: "", audio: "", text: "Hint not uploaded" },
      21: { image: "", audio: "", text: "Hint not uploaded" },
      22: { image: "", audio: "", text: "Hint not uploaded" },
      23: { image: "", audio: "", text: "Hint not uploaded" },
      24: { image: "", audio: "", text: "Hint not uploaded" },
      25: { image: "", audio: "", text: "Hint not uploaded" },
      26: { image: "", audio: "", text: "$(x^2 + y^2)^{3/2} = r$ and $text: `$x\\hat{i} + y\\hat{j} = \\vec{r}$`$" },
      27: { image: "", audio: "", text: "Hint not uploaded" },
      28: { image: "", audio: "", text: "Hint not uploaded" },
      29: { image: "", audio: "", text: "Hint not uploaded" },
      30: { image: "", audio: "", text: "Hint not uploaded" },
      31: { image: "", audio: "", text: "Hint not uploaded" },
      32: { image: "", audio: "", text: "Hint not uploaded" },
      33: { image: "", audio: "", text: "Hint not uploaded" },
      34: { image: "", audio: "", text: "Hint not uploaded" },
      35: { image: "", audio: "", text: "Hint not uploaded" },
      36: { image: "", audio: "", text: "Hint not uploaded" },
      37: { image: "", audio: "", text: "Hint not uploaded" },
      38: { image: "", audio: "", text: "Hint not uploaded" },
      39: { image: "", audio: "", text: "Hint not uploaded" },
      40: { image: "", audio: "", text: "Hint not uploaded" },
      41: { image: "", audio: "", text: "Hint not uploaded" },
      42: { image: "", audio: "", text: "Hint not uploaded" }
    }
  },
  "Exercise S": {
    totalQuestions: 30,
    hints: {
      1: { image: "", audio: "", text: "Hint not uploaded" },
      2: { image: "", audio: "", text: "Hint not uploaded" },
      3: { image: "", audio: "", text: "Hint not uploaded" },
      4: { image: "", audio: "", text: "Hint not uploaded" },
      5: { image: "", audio: "", text: "Hint not uploaded" },
      6: { image: "", audio: "", text: "Hint not uploaded" },
      7: { image: "", audio: "", text: "Hint not uploaded" },
      8: { image: "", audio: "", text: "Hint not uploaded" },
      9: { image: "", audio: "", text: "Hint not uploaded" },
      10: { image: "", audio: "", text: "Hint not uploaded" },
      11: { image: "", audio: "", text: "Hint not uploaded" },
      12: { image: "", audio: "", text: "Maximum tension at the bottom and minimum at top. Apply WET to get relation between the velocities." },
      13: { image: "", audio: "", text: "Hint not uploaded" },
      14: { image: "", audio: "", text: "Hint not uploaded" },
      15: { image: "", audio: "", text: "Hint not uploaded" },
      16: { image: "", audio: "", text: "Hint not uploaded" },
      17: { image: "", audio: "", text: "Hint not uploaded" },
      18: { image: "", audio: "", text: "Hint not uploaded" },
      19: { image: "", audio: "", text: "Hint not uploaded" },
      20: { image: "", audio: "", text: "Hint not uploaded" },
      21: { image: "", audio: "", text: "Hint not uploaded" },
      22: { image: "", audio: "", text: "Hint not uploaded" },
      23: { image: "", audio: "", text: "Hint not uploaded" },
      24: { image: "", audio: "", text: "Hint not uploaded" },
      25: { image: "", audio: "", text: "Solve in frame of the wedge. Find work done by pseudo force. Apply WET. In the critical condition the speed of block will just become zero when it reaches the top." },
      26: { image: "", audio: "", text: "Hint not uploaded" },
      27: { image: "", audio: "", text: "Hint not uploaded" },
      28: { image: "", audio: "", text: "Integrate power with respect to time" },
      29: { image: "", audio: "", text: "Hint not uploaded" },
      30: { image: "", audio: "", text: "Hint not uploaded" }
    }
  },
  "JEE Main": {
    totalQuestions: 33,
    hints: {
      1: { image: "", audio: "", text: "Hint not uploaded" },
      2: { image: "", audio: "", text: "Hint not uploaded" },
      3: { image: "", audio: "", text: "Hint not uploaded" },
      4: { image: "", audio: "", text: "Hint not uploaded" },
      5: { image: "", audio: "", text: "FInd acceleration then velocity then kinetic energy. Then WET" },
      6: { image: "", audio: "", text: "Hint not uploaded" },
      7: { image: "", audio: "", text: "Concept of circular motion. Given central force is the centripetal force. $$F = \\frac{k}{R^n} = m \\omega^2 R$$" },
      8: { image: "", audio: "", text: "Hint not uploaded" },
      9: { image: "", audio: "", text: "Hint not uploaded" },
      10: { image: "", audio: "", text: "Hint not uploaded" },
      11: { image: "", audio: "", text: "Hint not uploaded" },
      12: { image: "", audio: "", text: "Hint not uploaded" },
      13: { image: "", audio: "", text: "Hint not uploaded" },
      14: { image: "", audio: "", text: "Hint not uploaded" },
      15: { image: "", audio: "", text: "Hint not uploaded" },
      16: { image: "", audio: "", text: "Hint not uploaded" },
      17: { image: "", audio: "", text: "Hint not uploaded" },
      18: { image: "", audio: "", text: "Hint not uploaded" },
      19: { image: "", audio: "", text: "Integration application" },
      20: { image: "", audio: "", text: "Hint not uploaded" },
      21: { image: "", audio: "", text: "Hint not uploaded" },
      22: { image: "", audio: "", text: "Hint not uploaded" },
      23: { image: "", audio: "", text: "Hint not uploaded" },
      24: { image: "", audio: "", text: "Hint not uploaded" },
      25: { image: "", audio: "", text: "Hint not uploaded" },
      26: { image: "", audio: "", text: "Hint not uploaded" },
      27: { image: "", audio: "", text: "Hint not uploaded" },
      28: { image: "", audio: "", text: "Hint not uploaded" },
      29: { image: "", audio: "", text: "Hint not uploaded" },
      30: { image: "", audio: "", text: "Find acceleration. Integrate to get velocity. Then find power using $P = \\vec{F} \\cdot \\vec{v}$" },
      31: { image: "", audio: "", text: "Hint not uploaded" },
      32: { image: "", audio: "", text: "Hint not uploaded" },
      33: { image: "", audio: "", text: "Integration application. Variable force" }
    }
  },
  "JEE-Advanced": {
    totalQuestions: 20,
    hints: {
      1: { image: "", audio: "", text: "Hint not uploaded" },
      2: { image: "", audio: "", text: "Hint not uploaded" },
      3: { image: "", audio: "", text: "Hint not uploaded" },
      4: { image: "", audio: "", text: "Hint not uploaded" },
      5: { image: "", audio: "", text: "Hint not uploaded" },
      6: { image: "", audio: "", text: "Hint not uploaded" },
      7: { image: "", audio: "", text: "Hint not uploaded" },
      8: { image: "", audio: "", text: "Hint not uploaded" },
      9: { image: "", audio: "", text: "Hint not uploaded" },
      10: { image: "", audio: "", text: "Hint not uploaded" },
      11: { image: "", audio: "", text: "Hint not uploaded" },
      12: { image: "", audio: "", text: "Hint not uploaded" },
      13: { image: "", audio: "", text: "Hint not uploaded" },
      14: { image: "", audio: "", text: "Hint not uploaded" },
      15: { image: "", audio: "", text: "Hint not uploaded" },
      16: { image: "", audio: "", text: "Hint not uploaded" },
      17: { image: "", audio: "", text: "Hint not uploaded" },
      18: { image: "", audio: "", text: "Hint not uploaded" },
      19: { image: "", audio: "", text: "Hint not uploaded" },
      20: { image: "", audio: "", text: "Hint not uploaded" }
    }
  }
};
