// data.js - WEP Hints Data

const exercisesData = {
  "Exercise O-I": {
    totalQuestions: 30,
    hints: {
      1: { image: "", audio: "", text: "Vector concept. First find displacement vector then calculate DOT Product to get work. " },
      2: { image: "", audio: "", text: "Hint not uploaded" },
      3: { image: "", audio: "", text: "Hint not uploaded" },
      4: { image: "", audio: "", text: "First calculate tension using NLM concepts. Work done by rope implies work done by tension." },
      5: { image: "", audio: "", text: "Angle between force and displacement is $60 degree$" },
      6: { image: "", audio: "", text: "Hint not uploaded" },
      7: { image: "", audio: "", text: "Hint not uploaded" },
      8: { image: "", audio: "", text: "Hint not uploaded" },
      9: { image: "", audio: "", text: "Hint not uploaded" },
      10: { image: "", audio: "", text: "Hint not uploaded" },
      11: { image: "", audio: "", text: "Hint not uploaded" },
      12: { image: "", audio: "", text: "Area under F-x graph is Work done." },
      13: { image: "", audio: "", text: "Hint not uploaded" },
      14: { image: "", audio: "", text: "Hint not uploaded" },
      15: { image: "", audio: "", text: "Hint not uploaded" },
      16: { image: "", audio: "", text: "Hint not uploaded" },
      17: { image: "", audio: "", text: "Hint not uploaded" },
      18: { image: "", audio: "", text: "This is similar to free fall under gravity. Find displacements using Kinematics in the given intervals. Then find work in each interval." },
      19: { image: "", audio: "", text: "Use work-energy theorem. Find kinetic energy at $x=2$m. The given $a$ is just some constant and its units have been adjusted to match the dimensions on both sides. Don't worry about that." },
      20: { image: "", audio: "", text: "Hint not uploaded" },
      21: { image: "", audio: "", text: "Hint not uploaded" },
      22: { image: "", audio: "", text: "Hint not uploaded" },
      23: { image: "", audio: "", text: "Hint not uploaded" },
      24: { image: "", audio: "", text: "Hint not uploaded" },
      25: { image: "", audio: "", text: "Hint not uploaded" },
      26: { image: "", audio: "", text: "Hint not uploaded" },
      27: { image: "", audio: "", text: "Hint not uploaded" },
      28: { image: "", audio: "", text: "Hint not uploaded" },
      65: { image: "", audio: "", text: "text: `In Indian physics problems (especially Mechanics/Inclined planes) and railway gradient problems, "1 in $n$" or "$m$ in $n$" is often defined as the rise per unit distance measured <strong>along the incline</strong> itself:
$$\\sin \\theta = \\frac{\\text{Vertical Rise}}{\\text{Distance along the Incline}} = \\frac{2}{25} = 0.08$$`" },
      30: { image: "", audio: "", text: "Hint not uploaded" }
    }
  },
  "Exercise O-II": {
    totalQuestions: 15,
    hints: {
      1: { image: "", audio: "", text: "Hint not uploaded" },
      2: { image: "", audio: "", text: "Hint not uploaded" },
      3: { image: "", audio: "", text: "Hint not uploaded" },
      4: { image: "", audio: "", text: "Hint not uploaded" },
      5: { image: "", audio: "", text: "Hint not uploaded" },
      6: { image: "", audio: "", text: "Hint not uploaded" },
      7: { image: "", audio: "", text: "Hint not uploaded" },
      8: { image: "", audio: "", text: "Hint not uploaded" },
      9: { image: "", audio: "", text: "Hint not uploaded" },
      10: { image: "", audio: "", text: "Hint not uploaded" },
      11: { image: "", audio: "", text: "Hint not uploaded" },
      12: { image: "", audio: "", text: "Hint not uploaded" },
      13: { image: "", audio: "", text: "Hint not uploaded" },
      14: { image: "", audio: "", text: "Hint not uploaded" },
      15: { image: "", audio: "", text: "Hint not uploaded" }
    }
  },
  "Exercise S": {
    totalQuestions: 20,
    hints: {
      1: { image: "", audio: "", text: "Hint not uploaded" },
      2: { image: "", audio: "", text: "Hint not uploaded" },
      3: { image: "", audio: "", text: "Hint not uploaded" },
      4: { image: "", audio: "", text: "Hint not uploaded" },
      5: { image: "", audio: "", text: "Hint not uploaded" },
      6: { image: "", audio: "", text: "Hint not uploaded" },
      7: { image: "", audio: "", text: "Hint not uploaded" },
      8: { image: "", audio: "", text: "Hint not uploaded" },
      9: { image: "", audio: "", text: "Hint not uploaded" },
      10: { image: "", audio: "", text: "Hint not uploaded" },
      11: { image: "", audio: "", text: "Hint not uploaded" },
      12: { image: "", audio: "", text: "Hint not uploaded" },
      13: { image: "", audio: "", text: "Hint not uploaded" },
      14: { image: "", audio: "", text: "Hint not uploaded" },
      15: { image: "", audio: "", text: "Hint not uploaded" },
      16: { image: "", audio: "", text: "Hint not uploaded" },
      17: { image: "", audio: "", text: "Hint not uploaded" },
      18: { image: "", audio: "", text: "Hint not uploaded" },
      19: { image: "", audio: "", text: "Hint not uploaded" },
      20: { image: "", audio: "", text: "Hint not uploaded" }
    }
  },
  "JEE Main": {
    totalQuestions: 25,
    hints: {
      1: { image: "", audio: "", text: "Hint not uploaded" },
      2: { image: "", audio: "", text: "Hint not uploaded" },
      3: { image: "", audio: "", text: "Hint not uploaded" },
      4: { image: "", audio: "", text: "Hint not uploaded" },
      5: { image: "", audio: "", text: "Hint not uploaded" },
      6: { image: "", audio: "", text: "Hint not uploaded" },
      7: { image: "", audio: "", text: "Hint not uploaded" },
      8: { image: "", audio: "", text: "Hint not uploaded" },
      9: { image: "", audio: "", text: "Hint not uploaded" },
      10: { image: "", audio: "", text: "Hint not uploaded" },
      11: { image: "", audio: "", text: "Hint not uploaded" },
      12: { image: "", audio: "", text: "Hint not uploaded" },
      13: { image: "", audio: "", text: "Hint not uploaded" },
      14: { image: "", audio: "", text: "Hint not uploaded" },
      15: { image: "", audio: "", text: "Hint not uploaded" },
      16: { image: "", audio: "", text: "Hint not uploaded" },
      17: { image: "", audio: "", text: "Hint not uploaded" },
      18: { image: "", audio: "", text: "Hint not uploaded" },
      19: { image: "", audio: "", text: "Hint not uploaded" },
      20: { image: "", audio: "", text: "Hint not uploaded" },
      21: { image: "", audio: "", text: "Hint not uploaded" },
      22: { image: "", audio: "", text: "Hint not uploaded" },
      23: { image: "", audio: "", text: "Hint not uploaded" },
      24: { image: "", audio: "", text: "Hint not uploaded" },
      25: { image: "", audio: "", text: "Hint not uploaded" }
    }
  },
  "JEE-Advanced": {
    totalQuestions: 20,
    hints: {
      1: { image: "", audio: "", text: "Hint not uploaded" },
      2: { image: "", audio: "", text: "Hint not uploaded" },
      3: { image: "", audio: "", text: "Hint not uploaded" },
      4: { image: "", audio: "", text: "Hint not uploaded" },
      5: { image: "", audio: "", text: "Hint not uploaded" },
      6: { image: "", audio: "", text: "Hint not uploaded" },
      7: { image: "", audio: "", text: "Hint not uploaded" },
      8: { image: "", audio: "", text: "Hint not uploaded" },
      9: { image: "", audio: "", text: "Hint not uploaded" },
      10: { image: "", audio: "", text: "Hint not uploaded" },
      11: { image: "", audio: "", text: "Hint not uploaded" },
      12: { image: "", audio: "", text: "Hint not uploaded" },
      13: { image: "", audio: "", text: "Hint not uploaded" },
      14: { image: "", audio: "", text: "Hint not uploaded" },
      15: { image: "", audio: "", text: "Hint not uploaded" },
      16: { image: "", audio: "", text: "Hint not uploaded" },
      17: { image: "", audio: "", text: "Hint not uploaded" },
      18: { image: "", audio: "", text: "Hint not uploaded" },
      19: { image: "", audio: "", text: "Hint not uploaded" },
      20: { image: "", audio: "", text: "Hint not uploaded" }
    }
  }
};
