// data.js - Capacitance Hints Data

const exercisesData = {
  "Exercise O-I": {
    totalQuestions: 30,
    hints: {
      1: { image: "", audio: "", text: "Hint not uploaded" },
      2: { image: "", audio: "", text: "Hint not uploaded" },
      3: { image: "", audio: "", text: "Hint not uploaded" },
      4: { image: "", audio: "", text: "Hint not uploaded" },
      5: { image: "", audio: "", text: "Hint not uploaded" },
      6: { image: "", audio: "", text: "Hint not uploaded" },
      7: { image: "", audio: "", text: "Hint not uploaded" },
      8: { image: "", audio: "", text: "Hint not uploaded" },
      9: { image: "", audio: "", text: "Hint not uploaded" },
      10: { image: "", audio: "", text: "Hint not uploaded" },
      11: { image: "", audio: "", text: "Hint not uploaded" },
      12: { image: "", audio: "", text: "Hint not uploaded" },
      13: { image: "", audio: "", text: "Hint not uploaded" },
      14: { image: "", audio: "", text: "Hint not uploaded" },
      15: { image: "", audio: "", text: "Hint not uploaded" },
      16: { image: "", audio: "", text: "Hint not uploaded" },
      17: { image: "", audio: "", text: "Hint not uploaded" },
      18: { image: "", audio: "", text: "Hint not uploaded" },
      19: { image: "", audio: "", text: "Hint not uploaded" },
      20: { image: "", audio: "", text: "Hint not uploaded" },
      21: { image: "", audio: "", text: "Hint not uploaded" },
      22: { image: "", audio: "", text: "Hint not uploaded" },
      23: { image: "", audio: "", text: "Hint not uploaded" },
      24: { image: "", audio: "", text: "Hint not uploaded" },
      25: { image: "", audio: "", text: "Hint not uploaded" },
      26: { image: "", audio: "", text: "Hint not uploaded" },
      27: { image: "", audio: "", text: "Hint not uploaded" },
      28: { image: "", audio: "", text: "Hint not uploaded" },
      29: { image: "", audio: "", text: "Hint not uploaded" },
      30: { image: "", audio: "", text: "Hint not uploaded" }
    }
  },
  "Exercise O-II": {
    totalQuestions: 15,
    hints: {
      1: { image: "", audio: "", text: "Hint not uploaded" },
      2: { image: "", audio: "", text: "Hint not uploaded" },
      3: { image: "", audio: "", text: "Hint not uploaded" },
      4: { image: "", audio: "", text: "Hint not uploaded" },
      5: { image: "", audio: "", text: "Hint not uploaded" },
      6: { image: "", audio: "", text: "Hint not uploaded" },
      7: { image: "", audio: "", text: "Hint not uploaded" },
      8: { image: "", audio: "", text: "Hint not uploaded" },
      9: { image: "", audio: "", text: "Hint not uploaded" },
      10: { image: "", audio: "", text: "Hint not uploaded" },
      11: { image: "", audio: "", text: "Hint not uploaded" },
      12: { image: "", audio: "", text: "Hint not uploaded" },
      13: { image: "", audio: "", text: "Hint not uploaded" },
      14: { image: "", audio: "", text: "Hint not uploaded" },
      15: { image: "", audio: "", text: "Hint not uploaded" }
    }
  },
  "Exercise S": {
    totalQuestions: 20,
    hints: {
      1: { image: "", audio: "", text: "Hint not uploaded" },
      2: { image: "", audio: "", text: "Hint not uploaded" },
      3: { image: "", audio: "", text: "Hint not uploaded" },
      4: { image: "", audio: "", text: "Hint not uploaded" },
      5: { image: "", audio: "", text: "Hint not uploaded" },
      6: { image: "", audio: "", text: "Hint not uploaded" },
      7: { image: "", audio: "", text: "Hint not uploaded" },
      8: { image: "", audio: "", text: "Hint not uploaded" },
      9: { image: "", audio: "", text: "Hint not uploaded" },
      10: { image: "", audio: "", text: "Hint not uploaded" },
      11: { image: "", audio: "", text: "Hint not uploaded" },
      12: { image: "", audio: "", text: "Hint not uploaded" },
      13: { image: "", audio: "", text: "Hint not uploaded" },
      14: { image: "", audio: "", text: "Hint not uploaded" },
      15: { image: "", audio: "", text: "Hint not uploaded" },
      16: { image: "", audio: "", text: "Hint not uploaded" },
      17: { image: "", audio: "", text: "Hint not uploaded" },
      18: { image: "", audio: "", text: "Hint not uploaded" },
      19: { image: "", audio: "", text: "Hint not uploaded" },
      20: { image: "", audio: "", text: "Hint not uploaded" }
    }
  },
  "JEE Main": {
    totalQuestions: 25,
    hints: {
      1: { image: "", audio: "", text: "Hint not uploaded" },
      2: { image: "", audio: "", text: "Hint not uploaded" },
      3: { image: "", audio: "", text: "Hint not uploaded" },
      4: { image: "", audio: "", text: "Hint not uploaded" },
      5: { image: "", audio: "", text: "Hint not uploaded" },
      6: { image: "", audio: "", text: "Hint not uploaded" },
      7: { image: "", audio: "", text: "Hint not uploaded" },
      8: { image: "", audio: "", text: "Hint not uploaded" },
      9: { image: "", audio: "", text: "Hint not uploaded" },
      10: { image: "", audio: "", text: "Hint not uploaded" },
      11: { image: "", audio: "", text: "Hint not uploaded" },
      12: { image: "", audio: "", text: "Hint not uploaded" },
      13: { image: "", audio: "", text: "Hint not uploaded" },
      14: { image: "", audio: "", text: "Hint not uploaded" },
      15: { image: "", audio: "", text: "Hint not uploaded" },
      16: { image: "", audio: "", text: "Hint not uploaded" },
      17: { image: "", audio: "", text: "Hint not uploaded" },
      18: { image: "", audio: "", text: "Hint not uploaded" },
      19: { image: "", audio: "", text: "Hint not uploaded" },
      20: { image: "", audio: "", text: "Hint not uploaded" },
      21: { image: "", audio: "", text: "Hint not uploaded" },
      22: { image: "", audio: "", text: "Hint not uploaded" },
      23: { image: "", audio: "", text: "Hint not uploaded" },
      24: { image: "", audio: "", text: "Hint not uploaded" },
      25: { image: "", audio: "", text: "Hint not uploaded" }
    }
  },
  "JEE-Advanced": {
    totalQuestions: 20,
    hints: {
      1: { image: "", audio: "", text: "Hint not uploaded" },
      2: { image: "", audio: "", text: "Hint not uploaded" },
      3: { image: "", audio: "", text: "Hint not uploaded" },
      4: { image: "", audio: "", text: "Hint not uploaded" },
      5: { image: "", audio: "", text: "Hint not uploaded" },
      6: { image: "", audio: "", text: "Hint not uploaded" },
      7: { image: "", audio: "", text: "Hint not uploaded" },
      8: { image: "", audio: "", text: "Hint not uploaded" },
      9: { image: "", audio: "", text: "Hint not uploaded" },
      10: { image: "", audio: "", text: "Hint not uploaded" },
      11: { image: "", audio: "", text: "Hint not uploaded" },
      12: { image: "", audio: "", text: "Hint not uploaded" },
      13: { image: "", audio: "", text: "Hint not uploaded" },
      14: { image: "", audio: "", text: "Hint not uploaded" },
      15: { image: "", audio: "", text: "Hint not uploaded" },
      16: { image: "", audio: "", text: "Hint not uploaded" },
      17: { image: "", audio: "", text: "Hint not uploaded" },
      18: { image: "", audio: "", text: "Hint not uploaded" },
      19: { image: "", audio: "", text: "Hint not uploaded" },
      20: { image: "", audio: "", text: "Hint not uploaded" }
    }
  }
};
